# Generated by Django 3.0 on 2022-10-14 11:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Searoutes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('reverse_cost', models.FloatField(blank=True, null=True)),
                ('x1', models.FloatField(blank=True, null=True)),
                ('y1', models.FloatField(blank=True, null=True)),
                ('x2', models.FloatField(blank=True, null=True)),
                ('y2', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('source', models.BigIntegerField(blank=True, null=True)),
                ('target', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sea Routes',
                'db_table': 'searoutes',
            },
        ),
    ]
