# Generated by Django 3.0 on 2022-10-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiroutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('last', models.CharField(max_length=10)),
            ],
        ),
    ]
